### PR TITLE
chore: release main

### PR DESCRIPTION
**Pull request by MakMuftic**
:robot: I have created a release *beep* *boop*
---

<details><summary>sygmaprotocol-react-widget: 0.1.0</summary>

### Features

* base interface implementation for react package ([#61](https://github.com/sygmaprotocol/sygma-widget/issues/61)) ([0f38d7c](https://github.com/sygmaprotocol/sygma-widget/commit/0f38d7c785fe40a51b69ddc04b858b542c0ea1fd))
* EmvWallet class base implementation ([74c9649](https://github.com/sygmaprotocol/sygma-widget/commit/74c96492dba784524891dfa04ca3314c69a36370))

### Bug Fixes

* fix sygma namespace ([f9ab963](https://github.com/sygmaprotocol/sygma-widget/commit/f9ab9637ea2b797086cee6c0a12b046e3cb2e14c))

### Miscellaneous Chores

* **main:** release 0.0.1 ([8cff038](https://github.com/sygmaprotocol/sygma-widget/commit/8cff038e5ec68039a2b3ff0301f9d7d4b63d9f61))
* release 0.1.0 ([#101](https://github.com/sygmaprotocol/sygma-widget/issues/101)) ([c8f1aed](https://github.com/sygmaprotocol/sygma-widget/commit/c8f1aede49a480e4a6a5894857589c375457d5d4))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @buildwithsygma/sygmaprotocol-widget bumped to 0.1.0
</details>

<details><summary>sygmaprotocol-widget: 0.1.0</summary>

### Features

* action buttons v2 ([#91](https://github.com/sygmaprotocol/sygma-widget/issues/91)) ([5b2fbc5](https://github.com/sygmaprotocol/sygma-widget/commit/5b2fbc572efa9e9ca528159ecca6cd6be64365d0))
* add account balance refreshing for erc20 and evm native token ([#88](https://github.com/sygmaprotocol/sygma-widget/issues/88)) ([e135edc](https://github.com/sygmaprotocol/sygma-widget/commit/e135edcd1f569cb43d856ccb1ede5bf699787075))
* adding token balance to amount component ([c7b6268](https://github.com/sygmaprotocol/sygma-widget/commit/c7b6268053698a0b979f4faca9f3028e173cde0e))
* address to transfer ([#56](https://github.com/sygmaprotocol/sygma-widget/issues/56)) ([9fa87ad](https://github.com/sygmaprotocol/sygma-widget/commit/9fa87ad24762518cdcff10a0dd1aad5c844ce1dc))
* allow bridge environment configuration ([#104](https://github.com/sygmaprotocol/sygma-widget/issues/104)) ([7dd44e4](https://github.com/sygmaprotocol/sygma-widget/commit/7dd44e45d90468b0f0f69c381ebae7782226a697))
* amount input styles update ([#77](https://github.com/sygmaprotocol/sygma-widget/issues/77)) ([6101005](https://github.com/sygmaprotocol/sygma-widget/commit/61010050d0bd8602ea146e1a19045c4686e096b9))
* base implementation of network selector for the widget component ([b04ac49](https://github.com/sygmaprotocol/sygma-widget/commit/b04ac4952bfb775834cb1c7424f2ab3ed92dee33))
* base interface implementation for react package ([#61](https://github.com/sygmaprotocol/sygma-widget/issues/61)) ([0f38d7c](https://github.com/sygmaprotocol/sygma-widget/commit/0f38d7c785fe40a51b69ddc04b858b542c0ea1fd))
* base layout for widget + styles ([e259dca](https://github.com/sygmaprotocol/sygma-widget/commit/e259dca3719d96e0f8fedda8c3f711267c0a2ee0))
* changes to properties names ([291e753](https://github.com/sygmaprotocol/sygma-widget/commit/291e7535188f42b6a9f5bc4595e22901637446af))
* creation of mixin for property declaration and using component to render view ([d22772e](https://github.com/sygmaprotocol/sygma-widget/commit/d22772ea92cd088d571065b80f493f70a9f58cbd))
* EmvWallet class base implementation ([74c9649](https://github.com/sygmaprotocol/sygma-widget/commit/74c96492dba784524891dfa04ca3314c69a36370))
* evm and substrate wallet connection ([#72](https://github.com/sygmaprotocol/sygma-widget/issues/72)) ([ccf2049](https://github.com/sygmaprotocol/sygma-widget/commit/ccf2049b59da392789016774cff650d5b4491280))
* evm token transfer logic ([#95](https://github.com/sygmaprotocol/sygma-widget/issues/95)) ([7ae8547](https://github.com/sygmaprotocol/sygma-widget/commit/7ae85477e9c5481d30f4c5ce5a1ba737ce705895))
* externalize wallet connect connection through props ([#94](https://github.com/sygmaprotocol/sygma-widget/issues/94)) ([cc8617d](https://github.com/sygmaprotocol/sygma-widget/commit/cc8617dc76c32393c876d5151cfaa3a938af0564))
* improvements on selector implementation and misc changes ([940317f](https://github.com/sygmaprotocol/sygma-widget/commit/940317fcaa58478549afc615b1cddf9f8dcdac04))
* network selector component ([#70](https://github.com/sygmaprotocol/sygma-widget/issues/70)) ([003416e](https://github.com/sygmaprotocol/sygma-widget/commit/003416e66450f61cdefc7dd018a0aa10cbf34652))
* overlay ([#79](https://github.com/sygmaprotocol/sygma-widget/issues/79)) ([751ddb1](https://github.com/sygmaprotocol/sygma-widget/commit/751ddb15fbaaa7a20f11775beca3577e324e0793))
* remove wrong entrypoint for the widget ([9e0007e](https://github.com/sygmaprotocol/sygma-widget/commit/9e0007eb54a43bd2e8c79536b7d0bb8a9ef1a956))
* removing abi definition, calling sdk function to get balance and updating package.json file ([95b0653](https://github.com/sygmaprotocol/sygma-widget/commit/95b065369e7b7d86d1e5041285b5e2a53f35aced))
* renaming files, improvements over style and adding the components into the main layout ([edd4e35](https://github.com/sygmaprotocol/sygma-widget/commit/edd4e35118a0a0a992049a6319b63422ad4d838b))
* reset fields after transfer is complete  ([#163](https://github.com/sygmaprotocol/sygma-widget/issues/163)) ([762e95a](https://github.com/sygmaprotocol/sygma-widget/commit/762e95ae61f39f0a753e05677735466d8349e734)), closes [#133](https://github.com/sygmaprotocol/sygma-widget/issues/133)
* SDK Manager package ([#25](https://github.com/sygmaprotocol/sygma-widget/issues/25)) ([f9a8793](https://github.com/sygmaprotocol/sygma-widget/commit/f9a87932f5ffe7961c551e644ff20e2293fa4816))
* set destination address for EVM ([#129](https://github.com/sygmaprotocol/sygma-widget/issues/129)) ([679346a](https://github.com/sygmaprotocol/sygma-widget/commit/679346a4ea53bce5c424abbebfb59ee9a53e0c4e))
* small modifications to amount component and connect component ([1fda019](https://github.com/sygmaprotocol/sygma-widget/commit/1fda01945742580812ca45a22d21902638dfdc8f))
* transfer status ([#89](https://github.com/sygmaprotocol/sygma-widget/issues/89)) ([76c0265](https://github.com/sygmaprotocol/sygma-widget/commit/76c02659dde2decf4073d66ffb2cc35b8129cf41))
* upon clicking on max, render max value and trigger change event ([24746f5](https://github.com/sygmaprotocol/sygma-widget/commit/24746f5f5ecf66cfb6f800e6ea562e4a1d4927dd))
* utils functions, styles on diff file and rendering icons per chain id ([a2bc154](https://github.com/sygmaprotocol/sygma-widget/commit/a2bc154e3dc3530d99a1a476081971a9ba505f25))

### Bug Fixes

* add css reset ([#75](https://github.com/sygmaprotocol/sygma-widget/issues/75)) ([d512f58](https://github.com/sygmaprotocol/sygma-widget/commit/d512f5809a3b34e8507ab6f24c34f946ebcb201e))
* address input not submitted on paste ([#108](https://github.com/sygmaprotocol/sygma-widget/issues/108)) ([9acf7f0](https://github.com/sygmaprotocol/sygma-widget/commit/9acf7f05b5fdbe322b3e50a443735458f6537165))
* amount selector prefilled with zero ([#109](https://github.com/sygmaprotocol/sygma-widget/issues/109)) ([b178429](https://github.com/sygmaprotocol/sygma-widget/commit/b178429f46e84fdae49ed909b4f8cb0787cd477c))
* bug where user could proceed with invalid destination address ([#176](https://github.com/sygmaprotocol/sygma-widget/issues/176)) ([634a121](https://github.com/sygmaprotocol/sygma-widget/commit/634a1219429bdc9e3f0e5c96507d9cdae1bd4523)), closes [#164](https://github.com/sygmaprotocol/sygma-widget/issues/164)
* clear wallet context on disconnect ([#152](https://github.com/sygmaprotocol/sygma-widget/issues/152)) ([4a497e2](https://github.com/sygmaprotocol/sygma-widget/commit/4a497e2f86c863edc5991f2d9bc3906136321288))
* easier amount input ([#159](https://github.com/sygmaprotocol/sygma-widget/issues/159)) ([8d6620e](https://github.com/sygmaprotocol/sygma-widget/commit/8d6620e4fa98a98bb63c99a4dcf05f4e549cb92f))
* error where start new transfer isn't working ([#126](https://github.com/sygmaprotocol/sygma-widget/issues/126)) ([ca4ece0](https://github.com/sygmaprotocol/sygma-widget/commit/ca4ece01a49d4a321c0e38e14a3fae0ac7120050))
* evm amount is now calculated as user input minus the fee ([#143](https://github.com/sygmaprotocol/sygma-widget/issues/143)) ([d29771e](https://github.com/sygmaprotocol/sygma-widget/commit/d29771eaa87dd9d904f5780ede21e0b9ea0c9460))
* fix sygma namespace ([f9ab963](https://github.com/sygmaprotocol/sygma-widget/commit/f9ab9637ea2b797086cee6c0a12b046e3cb2e14c))
* incorrect transfer state when disconnecting wallet after transfer completed ([#130](https://github.com/sygmaprotocol/sygma-widget/issues/130)) ([359e6df](https://github.com/sygmaprotocol/sygma-widget/commit/359e6df08d7b0dbf29417d7b62974bc3f4b140e6))
* input type and conditional render for token icon ([25d7db3](https://github.com/sygmaprotocol/sygma-widget/commit/25d7db311587cf071541bdedc897526eedade7a0))
* linter issue with style module ([edc34bb](https://github.com/sygmaprotocol/sygma-widget/commit/edc34bbd1a4efd2504c71bd5f991821a5ebbd20f))
* max button rounds value ([#137](https://github.com/sygmaprotocol/sygma-widget/issues/137)) ([01901e6](https://github.com/sygmaprotocol/sygma-widget/commit/01901e67f2a1d28341878f0188a108ab1906e47b))
* misc fixes with icons ([#85](https://github.com/sygmaprotocol/sygma-widget/issues/85)) ([fedbcd9](https://github.com/sygmaprotocol/sygma-widget/commit/fedbcd9de3b0a16c19005e19249a5b0b2b7d69f7))
* prevent new lines and spaces in address input ([#81](https://github.com/sygmaprotocol/sygma-widget/issues/81)) ([44a318e](https://github.com/sygmaprotocol/sygma-widget/commit/44a318e26fc7cb5fbb73d3d5958fe4cf2ad46817))
* re-validate on account balance change ([#107](https://github.com/sygmaprotocol/sygma-widget/issues/107)) ([7935f81](https://github.com/sygmaprotocol/sygma-widget/commit/7935f8163ef1b95c8a32875427a2c0ab19baae3d))
* removing log ([71f42d6](https://github.com/sygmaprotocol/sygma-widget/commit/71f42d6831bf4109df363c5b42baedf469de826c))
* specific dispatchers either for network or token selector ([1ba9de3](https://github.com/sygmaprotocol/sygma-widget/commit/1ba9de3f1cfdff0ca9dd87a41672399971b958f8))
* substrate address not validated bug ([#128](https://github.com/sygmaprotocol/sygma-widget/issues/128)) ([74191b1](https://github.com/sygmaprotocol/sygma-widget/commit/74191b1d74de8c7526589722ea4c9f4431eaea1b))
* switch networks and misc fixes ([#127](https://github.com/sygmaprotocol/sygma-widget/issues/127)) ([db9ad8a](https://github.com/sygmaprotocol/sygma-widget/commit/db9ad8ac9f24fbd5bcb83c494b2579d1d023079f))
* Switching to a different TOKEN mapping for "From - TO" relationship is not updated in UI if amount is inserted ([#160](https://github.com/sygmaprotocol/sygma-widget/issues/160)) ([e2d16fd](https://github.com/sygmaprotocol/sygma-widget/commit/e2d16fd4182d328638904a86753f69417c6752a9))
* update sygma sdk version ([#82](https://github.com/sygmaprotocol/sygma-widget/issues/82)) ([6d8447a](https://github.com/sygmaprotocol/sygma-widget/commit/6d8447a88f5de824ce4b502d53dde0a321bffbd7))
* widget cloudflare deploy ([#68](https://github.com/sygmaprotocol/sygma-widget/issues/68)) ([fe6c36f](https://github.com/sygmaprotocol/sygma-widget/commit/fe6c36fc36c9043acd25a2f5e20ab64a52f45a9b))

### Miscellaneous Chores

* **main:** release 0.0.1 ([8cff038](https://github.com/sygmaprotocol/sygma-widget/commit/8cff038e5ec68039a2b3ff0301f9d7d4b63d9f61))
* release 0.1.0 ([#101](https://github.com/sygmaprotocol/sygma-widget/issues/101)) ([c8f1aed](https://github.com/sygmaprotocol/sygma-widget/commit/c8f1aede49a480e4a6a5894857589c375457d5d4))
</details>

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Comment by mpetrunic** [comment]
@LyonSsS Ready for QA!

**Comment by LyonSsS** [comment]
Existing issues for this version:

**Comment by LyonSsS** [comment]
Based on the design, the landing page of the widget, displays the option to Connect Wallet ( without choosing a From network option) and it has displayed an ERC20 place holder ( I may thing it is a default suggested token that exists in our ecosystem)

But on landing page of the current implementation, these options are not visible 

If you choose a FROM network, the Connect Wallet option will appear. 
Also if you choose destination, the ERC20 dropdown will be unlocked to choose some 


Do we need to do any changes here to match design or leave it as it is @itsbobbyzzz168  ?

**Comment by mpetrunic** [comment]
@LyonSsS Found two bugs that weren't reported:
- https://github.com/sygmaprotocol/sygma-widget/issues/133
- https://github.com/sygmaprotocol/sygma-widget/issues/132

**Comment by LyonSsS** [comment]
With the current status of the widget V 0.1.0, we can move on to release the first iteration and improve later. 
There is no Critical or High severity issue right now. 
CC: @MakMuftic  @mpetrunic  @itsbobbyzzz168

**Review by LyonSsS — COMMENTED** [review]
Tested on https://app.zenhub.com/workspaces/sygma-protocol-62f126a54b7d5a55203732f0/issues/gh/sygmaprotocol/sygma-widget/60 
Approve

**Review by LyonSsS — APPROVED** [review]

**Review by mpetrunic — APPROVED** [review]

**Comment by MakMuftic** [comment]
:robot: Release is at https://github.com/sygmaprotocol/sygma-widget/releases/tag/sygmaprotocol-react-widget-v0.1.0 :sunflower:

**Comment by MakMuftic** [comment]
:robot: Release is at https://github.com/sygmaprotocol/sygma-widget/releases/tag/sygmaprotocol-widget-v0.1.0 :sunflower:

**Pull request merged**
